language: java
sudo: required
jdk: oraclejdk8

services:
- docker

jobs:
  include:
    - stage: build
      script: mvn -B -V -DskipTests -DperformRelease -Dgpg.skip clean install
    - stage: test
      env: TYPE=glassfish-module
      script: .travis/tests.sh ${TYPE}
    - stage: test
      env: TYPE=glassfish-bundled
      script: .travis/tests.sh ${TYPE}
    - stage: test
      env: TYPE=testsuite-wildfly
      before_script: .travis/docker-wildfly.sh
      script: mvn -P${TYPE} --projects testsuite clean verify
    - stage: test
      env: TYPE=testsuite-payara
      before_script: .travis/docker-payara.sh
      script: mvn -P${TYPE} --projects testsuite clean verify
    - stage: test
      env: TYPE=tck-glassfish51-vanilla
      script: .travis/tests.sh ${TYPE}
    - stage: test
      env: TYPE=tck-glassfish51-patched
      script: .travis/tests.sh ${TYPE}
    - stage: test
      env: TYPE=tck-wildfly16-vanilla
      script: .travis/tests.sh ${TYPE}
    - stage: test
      env: TYPE=tck-wildfly16-patched
      script: .travis/tests.sh ${TYPE}
    - stage: test
      env: TYPE=tck-wildfly17
      script: .travis/tests.sh ${TYPE}
    - stage: test
      env: TYPE=tck-tomee
      script: .travis/tests.sh ${TYPE}
    - stage: test
      env: TYPE=tck-liberty
      script: .travis/tests.sh ${TYPE}
  allow_failures:
    - env: TYPE=tck-glassfish51-vanilla
    - env: TYPE=tck-wildfly16-vanilla
    - env: TYPE=tck-tomee
    - env: TYPE=tck-liberty
    - env: TYPE=testsuite-wildfly
    - env: TYPE=glassfish-module
